### ISSUE TITLE
no-complex-chaining errors.

### ISSUE THREAD

**Issue by JamieMason** [elijahmanor/eslint-plugin-smells#2]
I appreciate this is a new feature, but for tracking... when the following is enabled

``` json
"smells/no-complex-chaining": 1
```

This error is encountered

```
/usr/local/lib/node_modules/eslint-plugin-smells/lib/rules/no-complex-chaining.js:21
      if (callee && callee.object.type === 'CallExpression') {
                                 ^
TypeError: Cannot read property 'type' of undefined
    at levelOfChaining (/usr/local/lib/node_modules/eslint-plugin-smells/lib/rules/no-complex-chaining.js:21:34)
    at EventEmitter.CallExpression (/usr/local/lib/node_modules/eslint-plugin-smells/lib/rules/no-complex-chaining.js:32:11)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/usr/local/lib/node_modules/eslint/lib/eslint.js:725:25)
    at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/usr/local/lib/node_modules/eslint/lib/eslint.js:718:24)
    at processFile (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:197:27)
    at /usr/local/lib/node_modules/eslint/lib/cli-engine.js:332:26
    at /usr/local/lib/node_modules/eslint/lib/util/traverse.js:61:17
```

Thanks a lot.

**Comment by elijahmanor** [comment]
Just released a fix for this. Thanks for the comment!

**Comment by elijahmanor** [comment]
FYI, that rule is REALLY strict. I need to add support for options for several of these rules to make them more flexible (the above rule & the concat one)
